ACS\ACSPanelBundle\Entity\FosGroup:
    type: entity
    table: fos_group
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToMany:
        users:
            targetEntity: \ACS\ACSPanelUsersBundle\Entity\FosUser
            mappedBy: groups

    lifecycleCallbacks: {}

