settings:
    pattern:  /
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:userSettings" }

settings_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:show" }

settings_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:new" }

settings_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:create" }
    requirements: { _method: post }

settings_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:edit" }

settings_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:update" }
    requirements: { _method: post }

settings_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelSettingsBundle:ConfigSetting:delete" }
    requirements: { _method: post }
