parameters:
    # TODO: Set this value from config.yml
    acs_settings.settings.class: ACS\ACSPanelSettingsBundle\Doctrine\SettingManager
    acs_settings.system_settings.class: ACS\ACSPanelSettingsBundle\Modules\SystemSettings
    acs_settings.setting_class: ACS\ACSPanelBundle\Entity\PanelSetting
    acs_settings.home_base: "/home/"

services:
    acs.setting_manager:
        class: %acs_settings.settings.class%
        arguments: ['@doctrine.orm.entity_manager', %acs_settings.setting_class%, '@service_container']

    acs.system_setting_manager:
        class: %acs_settings.system_settings.class%

    # Menu items added with event listener
    settings_menu_subscriber:
        class: ACS\ACSPanelSettingsBundle\Event\Subscribers\SettingsMenuSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}

    # Settings related actions subscriber
    settings_subscriber:
        class: ACS\ACSPanelSettingsBundle\Event\Subscribers\SettingsSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}
