FOS\UserBundle\Model\User:
    xml_root_name: user
    properties:
        id:
            expose: true
        password:
            exclude: true
        email_canonical:
            exclude: true
        salt:
            exclude: true
        domains:
            exclude: true
