ACS\ACSPanelBundle\Entity\DB:
    type: entity
    repositoryClass: ACS\ACSPanelBundle\Model\DBRepository
    table: db
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 50
            fixed: false
            nullable: false
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    oneToMany:
        database_users:
            targetEntity: DatabaseUser
            mappedBy: db
            cascade: [ "persist" ]
    manyToOne:
        service:
            targetEntity: Service
            inversedBy: null
            joinTable: null
            orderBy: null
            joinColumn:
                onDelete: CASCADE

        user:
            targetEntity: FosUser
            cascade: {  }
            inversedBy: null
            joinTable: null
            orderBy: null
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue, setUserValue, createDatabase ]
      preUpdate: [ setUpdatedAtValue, updateDatabase ]
      preRemove: [ removeDatabase ]

