httpdalias:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:index" }

httpdalias_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:show" }

httpdalias_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:new" }

httpdalias_new_with_host:
    pattern: /{httpdhost_id}/new
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:new" }

httpdalias_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:create" }
    requirements: { _method: post }

httpdalias_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:edit" }

httpdalias_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:update" }
    requirements: { _method: post }

httpdalias_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:HttpdAlias:delete" }
    requirements: { _method: post }
