mailaliasdomain:
    pattern:  /
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:index" }

mailaliasdomain_show:
    pattern:  /{id}/show
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:show" }

mailaliasdomain_new:
    pattern:  /new
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:new" }

mailaliasdomain_create:
    pattern:  /create
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:create" }
    requirements: { _method: post }

mailaliasdomain_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:edit" }

mailaliasdomain_update:
    pattern:  /{id}/update
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:update" }
    requirements: { _method: post }

mailaliasdomain_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ACSACSPanelBundle:MailAliasDomain:delete" }
    requirements: { _method: post }
