parameters:
#    acsacs_panel_wordpress.example.class: ACS\ACSPanelWordpressBundle\Example

services:
#    acsacs_panel_wordpress.example:
#        class: %acsacs_panel_wordpress.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
