ACS\ACSPanelBundle\Entity\DnsRecord:
    type: entity
    table: dns_record
    gedmo:
        loggable: {}
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
            gedmo:
                - versioned
        type:
            type: string
            length: 6
            fixed: false
            nullable: false
            gedmo:
                - versioned
        content:
            type: string
            length: 255
            fixed: false
            nullable: true
            gedmo:
                - versioned
        ttl:
            type: integer
            unsigned: false
            nullable: true
            gedmo:
                - versioned
        prio:
            type: integer
            unsigned: false
            nullable: true
            gedmo:
                - versioned
        createdAt:
          type: datetime
          column: created_at
          gedmo:
            timestampable:
              on: create
        updatedAt:
          type: datetime
          column: updated_at
          nullable: true
          gedmo:
            timestampable:
              on: update
    manyToOne:
        domain:
            targetEntity: DnsDomain 
            cascade: {  }
            inversedBy: null
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                onDelete: CASCADE
        user:
            targetEntity: FosUser
            cascade: {  }
            inversedBy: null
            joinTable: null
            orderBy: null
            joinColumn:
                onDelete: CASCADE

    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue, setUserValue ]
      preUpdate: [ setUpdatedAtValue ]

