ACS\ACSPanelBundle\Entity\HttpdAlias:
    type: entity
    repositoryClass: ACS\ACSPanelBundle\Model\HttpdAliasRepository
    table: httpd_alias
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        enabled:
            type: boolean
            nullable: true 
        createdAt:
          type: datetime
          column: created_at
          gedmo:
            timestampable:
              on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                on: update
    oneToOne:
        domain:
            targetEntity: Domain
    lifecycleCallbacks:
      prePersist: [ setCreatedAtValue ]
      preUpdate: [ setUpdatedAtValue ]
