services:
    user_subscriber:
        class: ACS\ACSPanelBackupBundle\Event\UserSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}
    # Registering menu subscriber
    menu_subscriber:
        class: ACS\ACSPanelBackupBundle\Event\MenuSubscriber
        arguments: ['@event_dispatcher']
        tags:
            - {name: kernel.event_subscriber}
