ACS\ACSPanelWordpressBundle\Entity\WPSetup:
    type: entity
    table: wp_setup
    gedmo:
        loggable: {}
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        enabled:
            type: boolean
            nullable: true 
            gedmo:
                - versioned
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at

    manyToOne:
        user:
            targetEntity: ACS\ACSPanelBundle\Entity\FosUser
            cascade: {  }
            inversedBy: null
            joinTable: null
            orderBy: null
            gedmo:
                - versioned
            joinColumn:
                onDelete: CASCADE
    oneToOne:
        httpd_host:
            targetEntity: ACS\ACSPanelBundle\Entity\HttpdHost
            gedmo:
                - versioned
        database_user:
            targetEntity: ACS\ACSPanelBundle\Entity\DatabaseUser
            cascade: [ "persist" ]

    lifecycleCallbacks: {  }
