ACS\ACSPanelBundle\Entity\IpAddress:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: ip
    properties:
        ip:
            - Ip:  { version: all }

ACS\ACSPanelBundle\Entity\Domain:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: domain
    properties:
        domain:
            - Regex:
                pattern: "/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}$/"
                message: The domain must be valid domain name
            #- ACS\ACSPanelBundle\Validator\Constraints\DuplicateHost: 
                #target_entity: ACSACSPanelBundle:HttpdAlias
                #target_field: alias

#TODO: Check if is still needed
ACS\ACSPanelBundle\Entity\HttpdAlias:
    #constraints:
        #- Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: alias
    #properties:
        #alias:
            #- Regex:
                #pattern: "/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}$/"
                #message: The alias must be valid alias name
            #- ACS\ACSPanelBundle\Validator\Constraints\DuplicateHost: 
                #target_entity: ACSACSPanelBundle:HttpdHost
                #target_field: name

#TODO: Check if is still needed
ACS\ACSPanelBundle\Entity\PdnsDomain:
    #constraints:
        #- Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    #properties:
        #name:
            #- Regex:
                #pattern: "/^[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}$/"
                #message: The domain must be valid alias name
                #
ACS\ACSPanelBundle\Entity\FosUser:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: emailCanonical
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: usernameCanonical
